name: shopping_cart
version: 0.5.6
description: A Cloudstate Dart ShoppingCart Example.
author: Adriano Santos <sleipnir@bsd.com.br>
homepage: https://cloudstate.io
repository: https://github.com/sleipnir/cloudstate-dart-support.git

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  cloudstate: ^0.5.6
  #  path: ../../
  async: ^2.2.0
  grpc: ^2.1.3
  protobuf: ^1.0.1
